### ISSUE TITLE
Implement Cookie Management

### ISSUE THREAD

**Issue by npechl** [EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io#17]
Implement robust cookie management to enhance user experience and ensure compliance with privacy regulations.

Below are some usefull links:

- https://hugocodex.org/add-ons/cookie-consent/
- https://github.com/gohugoio/hugo/issues/10754

**Comment by graeme-a-stewart** [comment]
Hi @npechl - yes, if we set any cookies (at the moment we don't, so we're good there!) then we have to make them GPDR compliant. 

So a use case would be #25 (mostly for our own benefit). For "enhance user experience" did you have something in mind?

**Comment by graeme-a-stewart** [comment]
Merging this issue with #25
