### ISSUE TITLE
Add analytics (and cookie management)

### ISSUE THREAD

**Issue by fpsom** [EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io#25]
Google analytics might be an issue, so possibly also look into other solutions ([matomo](https://matomo.org/)?)

**Comment by graeme-a-stewart** [comment]
Adding @jmaassen here because we should indeed get the up and running (in a GPDR friendly way)

**Comment by egpbos** [comment]
We have a Matomo server running for our own websites (so GDPR compliant already) that we can also use for EVERSE.

**Comment by graeme-a-stewart** [comment]
That's excellent @egpbos - we should go ahead. There seem to be instructions here:

https://github.com/holehan/hugo-component-matomo

(I am surprised that they don't have Jekyll instructions!).

Do you have any experience with enabling it for Hugo? And what is the endpoint to send data to?

**Comment by graeme-a-stewart** [comment]
OK, I have had a go at this - it's not as trivial as I hoped!

- Thanks to NLeSC colleagues we have a Matomo endpoint and this is configured
  - This is also taking advantage of the Hugo Matomo "theme"
- I added a draft privacy page

However, I can't seem to get any data set that goes back to Matomo or sets the opt-in/opt-out options.

The current state is pushed to the [matomo branch](https://github.com/EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io/tree/matomo) in case anyone is inspired to take a look.
