### ISSUE TITLE
Clickable top-level link for one option menus

### ISSUE THREAD

**Issue by npechl** [EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io#45]
There was a comment in the D6.3 "Dissemination Plan" regarding the following:

"... but a menu with only one item could perhaps better be replaced with just a directly clickable top-level link. So instead of Services just make that the link to RSQkit and instead of Training make that go directly to the Training Events page."

One option menus could be replaced with top-level links:
- Services -> RSQkit
- Training -> Training events
- Participate -> How to Join

**Comment by graeme-a-stewart** [comment]
I think this one almost resolved itself. We suppressed the training menu for now (#67) and the Participate menu item has been folded into the Network tab.

For Services, we do anticipate more and I don't think it's that annoying.
