### ISSUE TITLE
Add Collaborations

### ISSUE THREAD

**Issue by aspaor** [EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io#57]
Create a section for Collaborations of EVERSE

**Comment by graeme-a-stewart** [comment]
Hi @aspaor - this is easy enough to do using the same model as we used for the consortium.

Do you want to tackle this one? I see you assigned yourself.

**Comment by aspaor** [comment]
Hi @graeme-a-stewart , yes I have already started working on this. I will let you know in case I need your help.

**Comment by graeme-a-stewart** [comment]
Would be fixed by #59
