### ISSUE TITLE
DNS error for everse.software

### ISSUE THREAD

**Issue by stain** [EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io#61]
```
everse.software.	1450	IN	A	185.199.109.153
everse.software.	1450	IN	A	185.199.108.153
everse.software.	1450	IN	A	185.199.110.153
everse.software.	1450	IN	A	192.64.119.71
everse.software.	1450	IN	A	185.199.111.153
```

the `192.64.119.71` does not respond to http or https and do not seem to be part of github pages. This causes 20% connection errors.

**Comment by graeme-a-stewart** [comment]
I gather from the Mattermost discussion that this was resolved, so I will close this - reopen if you still see issues.

Thanks for helping to get it sorted, @stain.
